Description: Serverless demo
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    CodeUri: ./dist
    Runtime: nodejs10.x

Resources:
  PostFoosToSQS:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PostFoosToSQSHandler.default
      MemorySize: 128
      Timeout: 5
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt FoosSQS.QueueName
      Events:
        FoosApiPostEvent:
          Type: Api
          Properties:
            Path: /foos/{foo}
            Method: POST
      Environment:
        Variables:
          QUEUE_URL: !Ref FoosSQS

  ProcessFoos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ProcessFoosHandler.default
      MemorySize: 128
      Timeout: 5
      Events:
        FoosApiPostEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FoosSQS.Arn
            BatchSize: 1

  FoosSQS:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 10 # this needs to be greater than ProcessFoos::Timeout

Outputs:
  Api:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/"
